base:
  process_count: 20
  count_per_process: 100000
  gen_voc: True

provider:
  text:
    - name: english
      path: data/corpus/word-en.txt
      probability: 0.2
      type: line
      len_range: (2,15)
    - name: chinese
      path: data/corpus/semtic_curpus.txt
      probability: 0.3
      type: line
      len_range: (2,15)
    - name: random_character
      path: data/corpus/chinese_synthetic.txt
      probability: 0.2
      type: word
      len_range: (2,15)
    - name: scene
      path: data/corpus/common.txt
      probability: 0.1
      type: line
      len_range: (2,15)
    - name: special
      path: data/corpus/huanbei.txt
      probability: 0.2
      type: line
      len_range: (2,15)
  smooth_area:
    down_scale: 32
    anchor_ratio: (0.17, 0.25, 0.5, 1.0, 2.0, 4.0, 6)
    anchor_scale: (8, 16, 24, 32, 48, 64, 72, 90)
  bg_img:
    - type: from_dir
      dir: /data/User/lijianan/data/ocr_background_img
      probability: 0.8
    - type: from_generate
      probability: 0.2
      width_range: (1000, 1500)
      height_range: (1000, 1500)
  text_img:
    font_file_dir: /data/User/hanat/TF_CRNN_CTC/data/fonts
    text_img_output_dir: /hanat/output/text_img
    text_img_info_output_dir: /hanat/output/text_img_info
    font_min_size: 20
    use_char_common_color_probability: 0.5
    char_common_color_list:
      - (0,0,0,255)
      - (255,0,0,255)
    char_border_width: 0
    char_border_color: (255,255,0,255)
  layout:
    out_put_dir: /hanat/output
    rotate_angle_range: (-8, 8)
    strategy_list:
      - name: HorizontalStrategy
        probability: 0.3
      - name: VerticalStrategy
        probability: 0.1
      - name: HorizontalFlowStrategy
        probability: 0.3
      - name: VerticalFlowStrategy
        probability: 0.1
      - name: RandomPasteStrategy
        probability: 0.1
      - name: CustomizationStrategy1
        probability: 0.1


